[package]
name = "sqlite3_unaccent"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rusqlite = { version = "0.36.0", features = ["loadable_extension", "functions"] }
deunicode = "1.6.2"
