default_job = "clippy"
env.CARGO_TERM_COLOR = "always"

# Clippy API
[jobs.clippy]
command = ["cargo", "clippy", "-p", "api"]
need_stdout = false
on_success = "job:run"

# Tests
[jobs.test]
command = ["cargo", "test"]
need_stdout = true
scroll_anchor = "last"

# Tests with logging
[jobs.test_log]
command = ["cargo", "test"]
need_stdout = true
env.TEST_LOG = "true"
scroll_anchor = "last"

# Unused dependencies
[jobs.udeps]
command = ["cargo", "+nightly", "udeps", "--workspace", "--all-targets"]
need_stdout = false
scroll_anchor = "last"

# Run API
[jobs.run]
command = [
    "cargo", "run", "-p", "api",
]
need_stdout = true
allow_warnings = true
background = false # For long-running applications (server)
on_change_strategy = "kill_then_restart"
scroll_anchor = "last"
