default_job = "clippy"
env.CARGO_TERM_COLOR = "always"

# Clippy API
[jobs.clippy]
command = ["cargo", "clippy", "-p", "api"]
need_stdout = false
on_success = "job:run"
scroll_anchor = "auto"

# Tests
[jobs.test]
command = ["cargo", "nextest", "run", "--workspace", "--all-targets", "--no-fail-fast"]
analyzer = "nextest"
need_stdout = true
scroll_anchor = "auto"

# Unused dependencies
[jobs.udeps]
command = ["cargo", "+nightly", "udeps", "--workspace", "--all-targets", "--all-features"]
need_stdout = true
scroll_anchor = "last"

# Audit dependencies
[jobs.audit]
command = ["cargo", "deny", "check", "advisories"]
need_stdout = true
scroll_anchor = "first"

# Run API
[jobs.run]
command = [
    "cargo", "run", "-p", "api",
]
need_stdout = true
allow_warnings = true
background = false # For long-running applications (server)
on_change_strategy = "kill_then_restart"
scroll_anchor = "auto"
