[workspace]
resolver = "3"
members = [
    "api",
    "api-error-derive",
    "coin-extractor",
    "update-agent",
]

[workspace.lints.clippy]
pedantic = {level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
redundant_closure_for_method_calls = "allow"
match_same_arms = "allow"
