services:
    finance:
        image: ghcr.io/v4ldum/finance:latest
        restart: unless-stopped
        read_only: true
        cap_drop: [ALL]
        security_opt: [no-new-privileges:true]
        tmpfs:
            - /tmp:mode=0700,uid=65532,gid=65532
        healthcheck:
            # Draining
            test: /bin/test ! -f /tmp/drain # && some other healthcheck
            interval: 5s
            retries: 1
        networks:
            - netv6
        environment:
            - TZ=Europe/Paris
            - HOST=0.0.0.0
            - PORT=7878
            # API logs as info, everything else as warn
            - RUST_LOG=warn,api=info
        volumes:
            - type: bind
              source: /root/finance/db/
              target: /app/db/
              # Volume instead of env_file because the deploy user don't have read permission on the environment files
            - type: bind
              source: /root/finance/secrets.env
              target: /app/.env
              read_only: true
        labels:
            dozzle.enable: true
            traefik.enable: true
            traefik.http.routers.finance.tls: true
            traefik.http.routers.finance.entrypoints: websecure
            traefik.http.middlewares.api-prefix.stripprefix.prefixes: /api
            traefik.http.routers.finance.middlewares: api-prefix
            traefik.http.routers.finance.rule: Host(`finance.valdum.dev`) && PathPrefix(`/api`)
            scheduler.enable: true
            scheduler.exec.update-precious-metals.schedule: 00 12 3 * * *
            scheduler.exec.update-precious-metals.command: /app/update-agent

networks:
    netv6:
        name: netv6
        external: true
