apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
    name: finance
    annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: api-prefix@file

spec:
    ingressClassName: traefik
    rules:
      - host: finance.lan
        http:
            paths:
              - path: /api
                pathType: Prefix
                backend:
                    service:
                        name: finance
                        port:
                            name: http

---
apiVersion: v1
kind: Service

metadata:
    name: finance

spec:
    type: ClusterIP
    selector:
        app: finance
    sessionAffinity: None
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: api

---
apiVersion: v1
kind: ConfigMap

metadata:
    name: finance

data:
    TZ: Europe/Paris
    HOST: 0.0.0.0
    PORT: "7878" # Needs stay in sync with containerPort in Deployment
    RUST_LOG: warn,api=info # API logs as info, everything else as warn
    DATABASE_URL: /app/db/finance.db?mode=rwc

---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: finance

spec:
    replicas: 1
    minReadySeconds: 15
    revisionHistoryLimit: 1

    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0

    selector:
        matchLabels:
            app: finance

    template:
        metadata:
            labels:
                app: finance

        spec:
            containers:
              - name: finance
                image: ghcr.io/v4ldum/finance:latest
                imagePullPolicy: Always

                ports:
                  - name: api
                    containerPort: 7878 # Needs to stay in sync with PORT in ConfigMap

                envFrom:
                  - configMapRef:
                        name: finance

                # Test every 5s for ~150s. Some migrations can take a while and we want to make sure they are finished before considering the pod won't start properly
                startupProbe:
                    periodSeconds: 5
                    failureThreshold: 30
                    httpGet:
                        path: /health/ready
                        port: api
                livenessProbe:
                    httpGet:
                        path: /health/live
                        port: api
                readinessProbe:
                    timeoutSeconds: 3
                    httpGet:
                        path: /health/ready
                        port: api

                volumeMounts:
                  - mountPath: /app/db
                    name: db

            volumes:
              - name: db
                hostPath:
                    path: /root/db/finance
                    type: Directory

---
apiVersion: batch/v1
kind: CronJob

metadata:
    name: finance-update

spec:
    schedule: "12 4 * * *"
    timeZone: Europe/Paris
    concurrencyPolicy: Forbid
    startingDeadlineSeconds: 300
    successfulJobsHistoryLimit: 0
    failedJobsHistoryLimit: 0

    jobTemplate:
        spec:
            backoffLimit: 0
            activeDeadlineSeconds: 120

            template:
                spec:
                    restartPolicy: Never

                    containers:
                      - name: finance-update
                        image: ghcr.io/v4ldum/finance:latest
                        imagePullPolicy: IfNotPresent

                        envFrom:
                          - configMapRef:
                                name: finance

                        command:
                          - /app/update-agent

                        volumeMounts:
                          - mountPath: /app/db
                            name: db

                    volumes:
                      - name: db
                        hostPath:
                            path: /root/db/finance
                            type: Directory
