DROP TABLE IF EXISTS cash_assets;
DROP TABLE IF EXISTS raw_assets;
DROP TABLE IF EXISTS coin_assets;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS coins;
DROP TABLE IF EXISTS coin_images;
DROP TABLE IF EXISTS prices;
