[package]
name = "update_agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
chrono = "0.4.37"
reqwest = { version = "0.12.2", default-features = false, features = ["json", "rustls-tls-native-roots"] }
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1.0.197", features = ["derive"] }
sqlx = { version = "0.8.3", features = ["sqlite", "runtime-tokio-rustls", "chrono"] }
